### ISSUE TITLE
Koodikatselmointi 2

### ISSUE THREAD

**Issue by JuhQ** [alehuo/clubhouse-backend#37]
Sivuston käytettävyydestä
  - tykkään sivuston yksinkertaisuudesta ja lookista
  - Rules sivu on tyhjä?
    - tarkoittaako tämä että klusterilla voi tehdä mitä vaan? ;)
  - register sivulla oleva gdpr checkboxin teksti voisi olla label, jota klikkaamalla checkbox aktivoituu
  - olisi jees jos rekisteröitymisen jälkeen käyttäjä kirjautuisi sisään automaattisesti
  - keys sivulla painelen `Send an email to keyholders` mutta mitään ei tapahdu? Pitäisikö joku viesti näkyä että email lähetetty tms?
  - headerin otsikko on linkki mutta ei ole kuitenkaan linkki?
    - klikkaamalla selain siirtyy etusivulle mutta hiiren kursori ei hoverissa muutu
  - sessioiden lisääminen ei lisää timelineen rivejä?

Frontend
  - niin paljon timanttista koodia, niin vähän testejä :D
  - koodi on pysynyt erittäin korkealaatuisena, taitojen ja typescriptin kanssa ei oikein voi mennä pieleen
  - edellisen katselmoinnin jälkeen on importtien järjestystä huomioitu - se on pieni detalji mutta vahva signaali
    - itse käytän vscodessa `sort imports` nimistä plugaria joka hoitaa tuon tallennuksen yhteydessä automaattisesti
  - tää on niin hyvää koodia että ainoa mitä nyt voin oikeastaan parannusehdotuksena antaa: CustomOverlay.tsx tiedostossa on
    ```
    delay={delay ? delay : 150}
    ```
    jonka ehkä voisi muuttaa muotoon
    ```
    delay={delay || 150}
    ```

Backend
  - ahh testejä!
  - ahh migraatioita!
  - koodi on timanttista!

Jepa jee, hyvää duunia tehty!

**Comment by alehuo** [comment]
Kiitos palautteesta! 😎
